"""RDF/OWL2 export for the cumulative conversation graph.

Converts the WEAID conversation graph into a standard semantic-web ontology
(Turtle format) with the SKD (Semantic / Kinetic / Dynamic) 3-layer model:

  * Classes      : weaid:Entity, weaid:Topic, skd:SemanticLayer, ...
  * Object props : weaid:causes, weaid:relatesTo, weaid:hasLayer
  * Data props   : weaid:predicate, weaid:turnText
  * Individuals  : every accumulated entity/topic, typed by SKD layer

This is the Palantir-Foundry-style ontology artifact: it can be loaded into
Protege, GraphDB, or any RDF triple store.
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

from core.graph_store import load

BASE_DIR = Path(__file__).resolve().parent.parent
EXPORT_DIR = BASE_DIR / "exports"
TURTLE_PATH = EXPORT_DIR / "weaid_ontology.ttl"

BASE = "https://weaid.ai/ontology#"
SKD = "https://weaid.ai/skd#"
XSD = "http://www.w3.org/2001/XMLSchema#"


def _t(s: str) -> str:
    """Escape a string for Turtle."""
    return str(s).replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")


def _iri(local: str) -> str:
    return f"<{BASE}{local}>"


def build_turtle(store: dict[str, Any] | None = None) -> str:
    store = store or load()
    lines: list[str] = [
        "@prefix weaid: <https://weaid.ai/ontology#> .",
        "@prefix skd:   <https://weaid.ai/skd#> .",
        "@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .",
        "@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .",
        "@prefix owl:   <http://www.w3.org/2002/07/owl#> .",
        "@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .",
        "",
        "# ── WEAID Ontology (SKD 3-layer) — generated by WEAID self-evolution engine ──",
        f"# created: {store.get('created', '')}  updated: {store.get('updated', '')}",
        f"# 창조자: 이길환 (HAPPYTALKMAN)",
        "",
        "weaid:Ontology a owl:Ontology ; rdfs:label \"WEAID Conversation Ontology\" .",
        "",
        "# Classes",
        "weaid:Entity  a owl:Class ; rdfs:label \"Entity\" .",
        "weaid:Topic   a owl:Class ; rdfs:subClassOf weaid:Entity ; rdfs:label \"Topic\" .",
        "skd:SemanticLayer a owl:Class ; rdfs:label \"Semantic — what something IS\" .",
        "skd:KineticLayer  a owl:Class ; rdfs:label \"Kinetic — what something DOES\" .",
        "skd:DynamicLayer  a owl:Class ; rdfs:label \"Dynamic — how things CHANGE\" .",
        "",
        "# Properties",
        "weaid:hasLayer a owl:ObjectProperty ; rdfs:domain weaid:Entity .",
        "weaid:causes   a owl:ObjectProperty ; rdfs:label \"causal relation\" .",
        "weaid:relatesTo a owl:ObjectProperty .",
        "weaid:hasPredicate a owl:DatatypeProperty ; rdfs:domain weaid:Entity ; rdfs:range xsd:string .",
        "weaid:turnText a owl:DatatypeProperty ; rdfs:range xsd:string .",
        "",
    ]

    entity_by_label = {e["label"]: e for e in store.get("entities", [])}

    def ent_iri(label: str) -> str:
        import re
        slug = re.sub(r"[^0-9A-Za-z가-힣_]", "_", str(label))[:60] or "anon"
        return f"weaid:e_{slug}"

    # Individuals: entities
    for e in store.get("entities", []):
        label = _t(e["label"])
        layer = str(e.get("layer", "semantic")).lower()
        layer_node = {"semantic": "skd:SemanticLayer", "kinetic": "skd:KineticLayer", "dynamic": "skd:DynamicLayer"}.get(layer, "skd:SemanticLayer")
        lines.append(
            f"{ent_iri(e['label'])} a weaid:Entity ; "
            f"rdfs:label \"{label}\" ; "
            f"weaid:hasLayer {layer_node} ; "
            f"weaid:occurrenceCount {int(e.get('count', 1))} ."
        )

    # Topics
    for t in store.get("topics", []):
        label = _t(t["label"])
        lines.append(
            f"{ent_iri(t['label'])} a weaid:Topic ; rdfs:label \"{label}\" ."
        )

    # Relations (causal ones typed explicitly)
    for r in store.get("relations", []):
        src, tgt = ent_iri(r["source"]), ent_iri(r["target"])
        label = _t(r["label"])
        prop = "weaid:causes" if r.get("kind") == "causal" else "weaid:relatesTo"
        lines.append(f"{src} {prop} {tgt} ; rdfs:label \"{label}\" .")

    # Turns (data provenance)
    for turn in store.get("turns", [])[-60:]:
        lines.append(
            f"weaid:turn{turn['seq']} a weaid:Entity ; "
            f"rdfs:label \"turn {turn['seq']} ({turn['speaker']})\" ; "
            f"weaid:turnText \"{_t(turn['text'][:400])}\" ."
        )

    # 대화 요약 노드 (자동 압축)
    for i, s in enumerate(store.get("summaries", [])):
        lines.append(
            f"weaid:summary{i} a weaid:Entity ; "
            f"rdfs:label \"요약 {s.get('start_turn')}~{s.get('end_turn')}\" ; "
            f"weaid:turnText \"{_t(s.get('summary', ''))}\" ."
        )

    return "\n".join(lines) + "\n"


def export_ontology(store: dict[str, Any] | None = None) -> Path:
    """Write the Turtle/OWL2 ontology file and return its path."""
    EXPORT_DIR.mkdir(parents=True, exist_ok=True)
    TURTLE_PATH.write_text(build_turtle(store), encoding="utf-8")
    return TURTLE_PATH


if __name__ == "__main__":
    import sys

    path = export_ontology()
    print(f"[RDF/OWL2] 내보내기 완료: {path}")
    sys.exit(0)
